GO
CREATE DATABASE Mis_Negocios
GO
USE Mis_Negocios
GO
CREATE SCHEMA VENTA
GO
CREATE TABLE VENTA.PAISES(
Idpais INT NOT NULL,
NombrePais VARCHAR(40) NOT NULL,
PRIMARY KEY(Idpais)
);
GO
CREATE SCHEMA CATEGORIA
GO
CREATE TABLE CATEGORIA.CATEGORIAS(
IdCategoria INT NOT NULL,
NombreCategoria VARCHAR(40) NOT NULL,
Descripcion TEXT NULL,
PRIMARY KEY(IdCategoria)
);
GO 
CREATE SCHEMA CLIENTE
GO
CREATE TABLE CLIENTE.CLIENTES(
Idcliente INT NOT NULL,
NomCliente VARCHAR(40) NOT NULL,
DirCliente VARCHAR(80) NOT NULL,
Idpais INT NOT NULL,
fonoCliente VARCHAR(15) NOT NULL
PRIMARY KEY(Idcliente),
FOREIGN KEY(Idpais) REFERENCES VENTA.PAISES(Idpais)
);
GO
CREATE SCHEMA PROVEEDOR
GO
CREATE TABLE PROVEEDOR.PROVEEDORES(
IdProveedor INT NOT NULL,
nomProveedor VARCHAR(80) NOT NULL,
dirProveedor VARCHAR(100) NOT NULL,
nomContacto VARCHAR(80) NOT NULL,
cargoContacto VARCHAR(50) NOT NULL,
idpais INT NOT NULL,
fonoProveedor VARCHAR(15) NOT NULL,
FAXpROVEEDOR VARCHAR(15) NOT NULL,
PRIMARY KEY(IdProveedor),
FOREIGN KEY(idpais) REFERENCES VENTA.PAISES(Idpais)
);
GO
CREATE SCHEMA PRODUCTO
GO
CREATE TABLE PRODUCTO.PRODUCTOS(
IdProducto INT NOT NULL,
nomProducto VARCHAR(80),
idProveedor int NOT NULL,
idCategoria INT NOT NULL,
cantxUnidad SMALLINT NOT NULL,
precioUnidad DECIMAL(10,2) NOT NULL,
UniEnExistencia SMALLINT NOT NULL,
UniEnPedido SMALLINT NOT NULL,
PRIMARY KEY(IdProducto),
FOREIGN KEY(idProveedor) REFERENCES PROVEEDOR.PROVEEDORES(idProveedor),
FOREIGN KEY(idCategoria) REFERENCES CATEGORIA.CATEGORIAS(IdCategoria)
);
GO
CREATE SCHEMA CARGO
GO 
CREATE TABLE CARGO.CARGOS(
IdCargo INT NOT NULL,
desCargo VARCHAR(30) NOT NULL,
PRIMARY KEY(IdCargo)
);
GO
CREATE SCHEMA DISTRITO
GO
CREATE TABLE DISTRITO.DISTRITOS(
IdDistrito INT NOT NULL,
nomDistrito VARCHAR(50) NOT NULL,
PRIMARY KEY(IdDistrito)
);
GO
CREATE SCHEMA EMPLEADO
GO
CREATE TABLE EMPLEADO.EMPLEADOS(
IdEmpleado INT NOT NULL,
nomEmpleado VARCHAR(50) NOT NULL,
apeEmpleado VARCHAR(50) NOT NULL,
fecNac DATETIME NOT NULL,
dirEmpelado VARCHAR(100) NOT NULL,
idDistrito INT NOT NULL,
fonoEmplado VARCHAR(15) NULL,
idcargo INT NOT NULL,
fecContrata DATETIME NOT NULL,
fotoEmpleado IMAGE NULL,
PRIMARY KEY(IdEmpleado),
FOREIGN KEY(idcargo) REFERENCES CARGO.CARGOS(IdCargo),
FOREIGN KEY(idDistrito) REFERENCES DISTRITO.DISTRITOS(IdDistrito)
);
GO
CREATE SCHEMA PEDIDO
GO
CREATE TABLE PEDIDO.PEDI(
IdPedido INT NOT NULL,
idcliente INT NOT NULL,
idEmpleado INT NOT NULL,
fechaPedido DATETIME NOT NULL,
fechaEntrega DATETIME NOT NULL,
fechaEnvio DATETIME NOT NULL,
enviopedido VARCHAR(15) NOT NULL,
destinatario VARCHAR(50) NOT NULL,
dirdestinatario VARCHAR(100) NOT NULL,
PRIMARY KEY(IdPedido),
FOREIGN KEY(idcliente) REFERENCES CLIENTE.CLIENTES(Idcliente),
FOREIGN KEY(idEmpleado) REFERENCES EMPLEADO.EMPLEADOS(IdEmpleado)
);
GO
CREATE SCHEMA PEDIDOSDE
GO
CREATE TABLE PEDIDOSDE.PEDIDOSDETA(
IdPedido INT NOT NULL,
idProducto INT NOT NULL,
precioUnidad DECIMAL(10,2) NOT NULL,
Cantidad SMALLINT NOT NULL,
Descuento DECIMAL(10,2) NOT NULL
FOREIGN KEY(IdPedido) REFERENCES PEDIDO.PEDI(IdPedido),
FOREIGN KEY(idProducto) REFERENCES PRODUCTO.PRODUCTOS(IdProducto)
);