CREATE FUNCTION DBO.MISREPORTES(@VAL REAL)
RETURNS TABLE 
AS

RETURN (SELECT CUS_FNAME AS 'NOMBRE',
CUS_LNAME AS 'APELLIDO',
CUS_BALANCE AS 'BALANCE'
FROM CUSTOMER
WHERE CUS_BALANCE >@VAL)
GO 

SELECT * FROM DBO.MISREPORTES(100)


CREATE FUNCTION DBO.SAL()
RETURNS TABLE 
AS 

RETURN (SELECT CUS_FNAME + ' '+ CUS_LNAME AS 'NOMBRE',
CUS_PHONE AS 'TELEFONO',
CUS_BALANCE AS 'SALDO'
FROM CUSTOMER
WHERE CUS_BALANCE = 0 )
GO 

SELECT * FROM DBO.SAL ()

SELECT * FROM CUSTOMER


CREATE FUNCTION DBO.VENTAS()

RETURNS TABLE

AS

RETURN (SELECT V_NAME AS 'NOMBRE',
V_CONTACT AS 'APELLIDO'
FROM VENDOR, 
PRODUCT WHERE  DBO.PRODUCT.V_CODE = DBO.VENDOR.V_CODE 
AND P_PRICE = (SELECT MAX (P_PRICE)
FROM PRODUCT)) 
GO

SELECT * FROM DBO.VENTAS()


CREATE FUNCTION DBO.FECHA()
RETURNS TABLE 
AS 

RETURN (SELECT CUS_CODE, CUS FROM CUSTOMER)


SELECT * FROM CUSTOMER

---------------------------------------------------

CREATE PROCEDURE INSERT_PRODUCT
@P_CODE NVARCHAR(10), @DESCRIP NVARCHAR(35),
@FECHA DATETIME,@CANTI SMALLINT,@MIN SMALLINT,
@PRECIO REAL, @DESC FLOAT,@V_CODE INT
AS
INSERT INTO PRODUCT
VALUES (@P_CODE,@DESCRIP,@FECHA,@CANTI,
@MIN,@PRECIO,@DESC,@V_CODE)

INSERT_PRODUCT '35RR721', 'SERRUCHO', '2014/03/06', 25, 15, 258, 25, 25600
